### ISSUE TITLE
Templates

### ISSUE THREAD

**Issue by jhalmeida** [sf-wdi-22-23/angular-ui-router-lab#2]
There are no templates in the starter code, so the app will break at the in UI-Router, instruction #4

**Comment by bgveenstra** [comment]
Ensured that starter code has templates and renamed templates/show.html to templates/wines-show.html to match README. Thanks!

**Comment by bgveenstra** [comment]
Oops, will be fixed once the review pull request is merged. Too hasty on my part

https://github.com/sf-wdi-22-23/angular-ui-router-lab/pulls
