### ISSUE TITLE
wine Show challenge

### ISSUE THREAD

**Issue by jhalmeida** [sf-wdi-22-23/angular-ui-router-lab#3]
I think $routeParams is only used with ngRoute and doesn't work here. In this case, I think $stateParams is needed.

**Comment by mtvillwock** [comment]
Yeah, I must have missed that when I was converting things. Good catch.

**Comment by mtvillwock** [comment]
I'm not seeing where you found that. Can you double check the `ui-router-solution` branch and let me know if it is still there?

**Comment by jhalmeida** [comment]
the instructions in, wine show challenge, call for $routeParams.

**Comment by bgveenstra** [comment]
found and fixed. Thanks Justin!

**Comment by bgveenstra** [comment]
Oops, will be fixed once the review pull request is merged. Too hasty on my part

https://github.com/sf-wdi-22-23/angular-ui-router-lab/pulls
