### ISSUE TITLE
injecting service

### ISSUE THREAD

**Issue by jhalmeida** [sf-wdi-22-23/angular-ui-router-lab#5]
I'm may have missed something but I was only able to get the service injection to work using this syntax: app.controller('WinesIndexCtrl', ['$scope', "WineService", function($scope, WineService) {...}])

**Comment by mtvillwock** [comment]
I'm not having the same issue, but it is a better practice to annotate your dependancies like that (otherwise it can break when minified, etc.).
I'll change it.
